version: "3.6"
services:
  bot:
    image: hanne-is-leuk-bot
    build: .
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - database-volume:/var/lib/postgresql/data

volumes:
  database-volume:
